### ISSUE TITLE
Helm으로 Prometheus 설치중 에러

### ISSUE THREAD

**Issue by Bro-o** [June222/cn2t4-infra#24]
Error: UPGRADE FAILED: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline

**Comment by Bro-o** [comment]
원인:
[EKS EBS CSI Driver](https://docs.aws.amazon.com/ko_kr/eks/latest/userguide/ebs-csi.html)
- pvc 볼륨 생성 안됨
<img width="783" alt="Image" src="https://github.com/user-attachments/assets/95f6fbd6-1821-4072-8d3c-6b8c4df6caca" />


\
해결:
- values.yaml에 PVC StorageClass를 명시해줌
```
server:
  persistentVolume:
      enabled: true
      storageClass: gp2
```
